version: '3.8'

services:
  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    image: restaurant/api-gateway-service:latest
    container_name: api-gateway-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: test
      JWT_SECRET: Fj93jsLk2mN7XyZ9wT1qU0oPrsVx5aKb
    depends_on:
      - auth-service
    networks:
      - restaurant-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: restaurant/auth-service:latest
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
