apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: restaurant
spec:
  selector:
    app: api-gateway-service
  ports:
    - port: 8081       # Cluster IP port
      targetPort: 8081 # Container port
      nodePort: 30081  # Exposed on your PC (change if you want)
  type: NodePort
