apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: restaurant/api-gateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
            - name: JWT_SECRET
              value: "Fj93jsLk2mN7XyZ9wT1qU0oPrsVx5aKb"
