apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: restaurant
spec:
  selector:
    app: auth-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP   # Internal-only, gateway talks to it
