package com.restaurant.tableorder.table_order_service.dto.Table;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for creating a new table.
 * Table number is always auto-generated by the system (fills gaps first, then increments from max).
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CreateTableDtoRequest {
    
    /** Maximum capacity of the table. */
    @NotNull(message = "Capacity is required")
    @Min(value = 1, message = "Capacity must be at least 1")
    private Integer capacity;
    
    /** Optional location/zone description. */
    @Size(max = 100, message = "Location cannot exceed 100 characters")
    private String location;
    
    /** Whether the table is active (default: true). */
    private Boolean isActive;
}

